image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/

lint:
  stage: test
  script:
    - npm ci
    - npm run lint
  allow_failure: true

pages:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  script:
    - mkdir .public
    - cp -r dist/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
