image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm ci
    - npm run prepare
  artifacts:
    paths:
      - dist/
      - lib/

lint:
  stage: test
  script:
    - npm ci
    - npm run lint
    - npm run pretty
  allow_failure: true

pages:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  script:
    - mkdir .public
    - cp -r dist/* .public
    - cp -r lib/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'

publish:
  stage: deploy
  script:
    - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish
  rules:
    - if: $CI_COMMIT_TAG
